version: '3.3'

services:
  mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - ./mongo_data:/data/db

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017/turismo-GAMC
      NODE_ENV: production
      SSL_KEY_PATH: /src/certs/privatekey_sp.key
      SSL_CERT_PATH: /src/certs/cochabamba.bo.crt
    volumes:
      - ./certs:/src/certs
    depends_on:
      - mongo

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx-config:/etc/nginx/conf.d
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - nestjs-app
  #   networks:
  #     - frontend-network

# networks:
#   frontend-network:
#     driver: bridge